services:
  server:
    image: taskflow-server:latest
    pull_policy: never
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    image: taskflow-client:latest
    pull_policy: never
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    restart: unless-stopped